name: flutter_analytics_example
version: 0.6.7+5

environment:
  flutter: ^1.5.3
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_analytics:
    path: ../

flutter:
  assets:
    - .config_url
  uses-material-design: true
