name: flutter_analytics_example
description: an example
version: 0.6.7+5

environment:
  flutter: ^1.5.4-hotfix.2
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_analytics:
    path: ../

flutter:
  uses-material-design: true
