name: flutter_analytics
description: A barebones Analytics SDK to collect anonymous metadata from flutter apps.
version: 0.3.3
author: Romulo Carvalho <oakromulo@gmail.com>
homepage: https://github.com/oakromulo/flutter_analytics
repository: https://github.com/oakromulo/flutter_analytics.git
issue_tracker: https://github.com/oakromulo/flutter_analytics/issues

environment:
  flutter: ^1.5.4-hotfix.2
  sdk: ">=2.3.0-dev.0.5 <3.0.0"

dependencies:
  connectivity: ^0.4.3+2
  device_info: ^0.4.0+2
  devicelocale: ^0.1.1
  flutter:
    sdk: flutter
  flutter_persistent_queue: ^3.0.0
  flutter_udid: ^1.0.0
  http: ^0.12.0+2
  localstorage: ^2.0.0
  package_info: ^0.4.0+4
  uuid: ^2.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
