name: flutter_analytics
description: A barebones Analytics SDK to collect anonymous metadata from flutter apps.
version: 1.1.0
author: Romulo Carvalho <oakromulo@gmail.com>
homepage: https://github.com/oakromulo/flutter_analytics
repository: https://github.com/oakromulo/flutter_analytics.git
issue_tracker: https://github.com/oakromulo/flutter_analytics/issues

environment:
  flutter: '>1.7.8 <2.0.0'
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  connectivity: ^0.4.5
  device_info: ^0.4.0+4
  devicelocale: ^0.2.0
  flutter:
    sdk: flutter
  flutter_persistent_queue: ^5.0.1
  flutter_udid: ^1.0.1
  http: ^0.12.0+2
  localstorage: ^2.0.0
  package_info: ^0.4.0+9
  path_provider: ^1.3.1
  uuid: ^2.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
