name: flutter_analytics
description: A barebones Analytics SDK to collect anonymous metadata from flutter apps.
publish_to: none
version: 7.5.3
homepage: https://github.com/oakromulo/flutter_analytics
repository: https://github.com/oakromulo/flutter_analytics.git
issue_tracker: https://github.com/oakromulo/flutter_analytics/issues

environment:
  flutter: '>=1.12.13+hotfix.5 <2.0.0'
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  connectivity: ^3.0.3
  device_info: ^2.0.0
  devicelocale: ^0.3.3
  flutter:
    sdk: flutter
  flutter_persistent_queue:
    git: https://github.com/fanhero/flutter_persistent_queue.git
  flutter_udid: ^1.0.1
  http: ^0.13.1
  location: ^4.1.1
  package_info: ^2.0.0
  path_provider: ^2.0.1
  recase: ^3.0.1
  sim_info: ^0.1.3
  uuid: ^3.0.3

dev_dependencies:
  test: any
