name: flutter_analytics
description: A barebones Analytics SDK to collect anonymous metadata from flutter apps.
version: 7.5.1
homepage: https://github.com/oakromulo/flutter_analytics
repository: https://github.com/oakromulo/flutter_analytics.git
issue_tracker: https://github.com/oakromulo/flutter_analytics/issues

environment:
  flutter: '>=1.12.13+hotfix.5 <2.0.0'
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  connectivity: ^0.4.9+2
  device_info: ^0.4.2+7
  devicelocale: ^0.3.1
  flutter:
    sdk: flutter
  flutter_persistent_queue: ^6.1.1
  flutter_udid: ^1.0.1
  http: ^0.12.2
  location: ^3.0.2
  package_info: '>=0.4.3 <2.0.0'
  path_provider: ^1.6.14
  recase: ^3.0.0
  sim_info: ^0.1.1
  uuid: ^2.2.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
