name: flutter_analytics
description: A barebones Analytics SDK to collect anonymous metadata from flutter apps.
version: 6.0.1
homepage: https://github.com/oakromulo/flutter_analytics
repository: https://github.com/oakromulo/flutter_analytics.git
issue_tracker: https://github.com/oakromulo/flutter_analytics/issues

environment:
  flutter: '>=1.12.13+hotfix.5 <2.0.0'
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  connectivity: ^0.4.6+2
  device_info: ^0.4.1+4
  devicelocale: ^0.2.1
  flutter:
    sdk: flutter
  flutter_persistent_queue: ^5.1.1
  flutter_udid: ^1.0.1
  http: ^0.12.0+4
  localstorage: ^3.0.1+4
  location: ^2.3.5
  package_info: ^0.4.0+13
  path_provider: ^1.6.0
  recase: ^3.0.0
  uuid: ^2.0.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
